### ISSUE TITLE
Not accounting for "params" request parameter

### ISSUE THREAD

**Issue by moltar** [jamesmbourne/aws4-axios#10]
axios has a request option named `params`, which gets converted to the query string.

This library does not take that into account, and all of the params are simply dropped.

The workaround is to supply params in the request URL manually.

**Comment by cohlar** [comment]
Same issue here, I currently pass params in the URL but it would be nice to also support a `params` object.
@jamesmbourne I'd be glad to propose a PR if you agree it's relevant

**Comment by moltar** [comment]
@jamesmbourne using it for SP API too? Writing a client by any chance?

**Comment by florianbepunkt** [comment]
Solved in PR #34 

Tested it with an SP API call.

**Comment by jamesmbourne** [comment]
This has been released in v2.1.0 - please let me know if you have any problems!

Thanks @moltar @florianbepunkt @cohlar for your contributions on this 🥇
