### ISSUE TITLE
Calming down of Renovate

### ISSUE THREAD

**Issue by moltar** [jamesmbourne/aws4-axios#1022]
Hey, I think we need to calm renovate bot down a bit. I am a big fan of it, and use it on all my projects. But when it comes specifically to _some_ packages, there are way too many updates and then `aws4-axios` releases, that do not meaningfully affect the package.

A few things I would optimize:

- Set dev deps to `chore` and thereby do not trigger a release.
  - If using Semantic Release, then this is automatic
  - Otherwise can do something like filter for `[skip-ci]` on the release workflow in GH Actions. Then configure Renovate to include that message in the body or subject.
- Configure an alternative schedule for some packages. Notably:
  - `constructs` - this package gets released way too much. Almost never there is a meaningful change. All of the releases are due to dependency upgrades. This package is a requirement of CDK. I set this to update every 3 months.
  - `aws-cdk-lib` - this gets a minimum of 1 weekly release, and sometimes more due to bug fix releases. This is only used for dev deps for infra deployment, which is very simple and unlikely to change. I'd set this to update at a maximum of once a month. There are almost never any big meaningful changes in CDK-land. Mostly just new services being added, and new features bolted on. But for a basic integ suite that just tests AWS 4 signature, this will have no effect.

**Comment by jamesmbourne** [comment]
Hey @moltar, thanks for the feedback and apologies for the excess noise this created.

I'll try moving these deps to `devDependencies` and see if that sorts it out.
