### ISSUE TITLE
error throwing when call api

### ISSUE THREAD

**Issue by sivarasanOensys** [jamesmbourne/aws4-axios#12]
TypeError: url_1.URL is not a constructor
    at interceptor.js:51

**Comment by moltar** [comment]
@sivarasanOensys this issue needs more details, otherwise the author will not be able to help.

At a minimum you need to provide a code example of how you make the call.

Ideally, please provide a reproduction demo.

**Comment by jamesmbourne** [comment]
@sivarasanOensys I believe this should be fixed in https://github.com/jamesmbourne/aws4-axios/commit/33dc444f31e11cd03152b74b50ec4ee0a8162857. Please open another issue if you are still encountering this issue when using the [latest version v2.2.0](https://www.npmjs.com/package/aws4-axios/v/2.2.0).
