### ISSUE TITLE
Unable to use it with React JS 

### ISSUE THREAD

**Issue by shounaklohokare** [jamesmbourne/aws4-axios#1237]
Hi folks, 

I tried using this in plain NodeJS invoking a AWS_IAM authorized API Gateway Method, but I am not able to use this library with React JS,
I am getting the following run time error. 

 TypeError: instance.getUri is not a function
    at interceptor.js:70:1
    at Generator.next (<anonymous>)
    at interceptor.js:8:1
    at new Promise (<anonymous>)
    at __webpack_modules__../node_modules/aws4-axios/dist/interceptor.js.__awaiter (interceptor.js:4:1)
    at interceptor.js:69:1

Any help is appreciated,
Thanks

**Comment by mohamed-ali-halloul** [comment]
Hello can i make this issue
Cordialement
