### ISSUE TITLE
Does Not Support Axios Instance BaseURL

### ISSUE THREAD

**Issue by CoshUS** [jamesmbourne/aws4-axios#1245]
### Summary
Axios calls interceptor with `baseURL` and `url` in the config. However, aws4-axios only checks `config.url`:
https://github.com/jamesmbourne/aws4-axios/blob/7e2e858e630a6c0dc9ba1c16bbdb7af8fd4a63c6/src/interceptor.ts#L126C23-L126C23.

`No URL present in request config, unable to sign request` is thrown if url is passed in with as an empty string.

### Example code:
```
const instance = axios.create({baseURL: "https://example.com/");
instance.interceptors.request.use(aws4Interceptor({
        options: {
            region: process.env.AWS_REGION,
            service: "example"
        }
}));
//Empty URL here
const response = await instance.post("", {});
...
```

### Config object:
```
{
    ...
    "baseURL": "https://example.com/",
    "url": "",
    "data": "{}",
    ...
}
```

**Comment by mohamed-ali-halloul** [comment]
Hello can i make this issue ?
Have a nice day

**Comment by mohamed-ali-halloul** [comment]
Hello can i word in this issue?
Thank you
