### ISSUE TITLE
Snyk vulnerability 

### ISSUE THREAD

**Issue by nauma-yuvital** [jamesmbourne/aws4-axios#1382]
Hi,
We're getting this error from Snyk for version @3.3.4

![snykAwsErr](https://github.com/jamesmbourne/aws4-axios/assets/109896367/e1313209-97b9-4f37-895d-0a16b40a8698)

**Comment by jamesmbourne** [comment]
This is fixed in https://github.com/jamesmbourne/aws4-axios/releases/tag/v3.3.6
