### ISSUE TITLE
Snyk vulnerability - fast-xml-parser

### ISSUE THREAD

**Issue by GregMotorpoint** [jamesmbourne/aws4-axios#1425]
https://security.snyk.io/vuln/SNYK-JS-FASTXMLPARSER-5777726

Dependabot on our own repo has this:

"aws4-axios@3.3.4 requires fast-xml-parser@4.2.4 via a transitive dependency on @aws-sdk/client-sts@3.352.0"

Its a low vulnerability, but would be nice to fix if possible - looks like the version of fast-xml-parser has been upgraded to 4.2.5 in a more recent version of aws-sdk/client-sts - is it possible to get the dependency on this updated?

Thanks.

**Comment by jamesmbourne** [comment]
Duplicate of #1382
