### ISSUE TITLE
Refactor to use AWS SDK v3 signing package

### ISSUE THREAD

**Issue by moltar** [jamesmbourne/aws4-axios#35]
AWS SDK v3 was officially released: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/

Benefits:

 * It is modular as opposed to the original monolith (`aws-sdk@2`).
 * It is written in TypeScript.
 * It includes the signing package: [@aws-sdk/signature-v4](https://github.com/aws/aws-sdk-js-v3/tree/master/packages/signature-v4)
 * Supported by AWS / Amazon

**Comment by jamesmbourne** [comment]
Hey @moltar, thanks for letting me know about this! I'll take a look into it 👍
