### ISSUE TITLE
Is it intended to work with custom API Gateway domains?

### ISSUE THREAD

**Issue by eran-medan** [jamesmbourne/aws4-axios#397]
It works like a charm with the default API Gateway endpoints, but when switching to a custom domain it returns a 403... is that as designed? Or an issue?

**Comment by jamesmbourne** [comment]
Hey @eran-medan - yes it should do. What type of custom domain are you using? I believe you might need to change the region if you use an edge-optimized custom domain to use `us-east-1`.

https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-edge-optimized-custom-domain-name.html
