### ISSUE TITLE
Is aws4-axios intended to be used from a client-side app?

### ISSUE THREAD

**Issue by matheuseabra** [jamesmbourne/aws4-axios#510]
Hey folks, nice job with this lib.

I was wondering if this can be safely be used to sign HTTP requests, being made from a React client-side app that makes GET requests to AWS S3 bucket URL that us AWS-KMS encryption for bucket objects

Thanks!

**Comment by Pinwheeler** [comment]
You can use STS to obtain credentials with [AssumeRoleWithWebIdentity](https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role-with-web-identity.html)
