### ISSUE TITLE
Assume and cache role for cross-account request

### ISSUE THREAD

**Issue by m-radzikowski** [jamesmbourne/aws4-axios#59]
Hello,
this interceptor is great when you do the requests in the scope of the same AWS account. But when you want to make cross-account request with IAM signature the workflow is as follows:

- assume a role from another account using AWS STS SDK
- sign request with assumed role credentials
- use the same (cached) credentials for the next requests, unless they expired - then assume the role again

Because the interceptor requires providing the credentials in config param, to use it you have to handle credentials cache, expiration, and re-create axios instance in some kind of wrapper.

Instead, I use a similar interceptor that allows providing a Role ARN to assume as a parameter. It handles assuming role and caching it.

If you are open to it, I would like to integrate it with this library. The changes would include:

- a new dependency on `@aws-sdk/client-sts`
- new optional parameters in `InterceptorOptions`:
  - `assumeRoleArn`
  - `assumedRoleExpirationMarginSec` - to refresh the credentials if the expiration time is closer than the given number of seconds
- creating 2 `CredentialsProvider` classes to provide credentials for a signature, one for current behavior (when they are provided in options or not at all) and second for obtaining them from the assumed role.

Those should be non-breaking changes.

Please let me know if you want me to create a PR with this implementation. I have the logic ready, it's only a matter of integrating it with the library. Otherwise, I will publish it as a separate package. But to be honest I think it's better to extend existing libraries instead of creating new separate ones.

**Comment by jamesmbourne** [comment]
Hey @m-radzikowski, that sounds like it could be a really useful addition to the project!

Feel free to open a PR and I'll be happy to take a look over it 👍
