### ISSUE TITLE
Access to XMLHttpRequest at 'https://<AWS-LAMBDA-FUNCTION-URL>' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by yaelsprikut** [jamesmbourne/aws4-axios#671]
Hi,

I'm running into some CORS errors when sending a GET request to my lambda service's function URL. I've tested this request with Postman and it's returning 200 ok. But when I try the same request in the browser it throws a CORS error.

Here's my init code: 
```
export const axios = require('axios').default
import { aws4Interceptor } from 'aws4-axios'

const interceptor = aws4Interceptor(
    {
        region: 'us-east-1',
        service: 'lambda',
    },
    {
        accessKeyId: 'ACCESS-ID',
        secretAccessKey: 'SECRET-KEY',
    }
)
axios.interceptors.request.use(interceptor)
```

And then it's just a simple `axios.get()` request to the `AWS-LAMBDA-FUNCTION-URL`. 

Am I missing something?

Thanks!

**Comment by jamesmbourne** [comment]
Hey @yaelsprikut, it sounds like this is likely issue with your Lambda function not returning the appropriate CORS headers. Postman does not enforce CORS in the same way your browser does, so is not a reliable way to reproduce this kind of issue.

You can find more about CORS here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.
