### ISSUE TITLE
url_1.URL is not a constructor

### ISSUE THREAD

**Issue by jasonhaihuang** [jamesmbourne/aws4-axios#7]
I am having ".URL is not a constructor" error as following. 

`TypeError: url_1.URL is not a constructor  at eval (interceptor.js?e311:51)`

dependency:
`    "aws4-axios": "^1.12.0",
    "core-js": "^3.6.5",
    "moment": "^2.27.0",
    "vue": "^2.6.11",
    "vue-router": "^3.2.0",
    "vuelidate": "^0.7.5",
    "vuetify": "^2.2.11",
    "vuex": "^3.4.0"
`

My code is like this:
`===============================code starts=====================================
const axios = require('axios');

  const interceptor = aws4Interceptor({
    region: Environment.aws.api.region,
    service: Environment.aws.api.service
  }, {
    accessKeyId: Environment.aws.api.accessKeyId,
    secretAccessKey: Environment.aws.api.secretAccessKey
  });

  client.interceptors.request.use(interceptor);
  const reqUrl = ' https://xxxxxxxx.execute-api.xxxxxxxxxx.amazonaws.com/Dev/bookinfo/1234567890';

  client.get(reqUrl).then(res => {
    console.log('aws req succ. ', res);
  }).catch(error => {
    console.log('aws req fail. ', error);
  }).finally(() => {
    //
  });
============================code ends===================================`

And the error seems to complain about something in the following interceptor code.

`exports.aws4Interceptor = function (options, credentials) { return function (config) {
    ...
    var _a = new url_1.URL(url), host = _a.host, pathname = _a.pathname, search = _a.search;
    ...
}`

Any idea about this issue? Where should I look into? Thanks.

**Comment by jasonhaihuang** [comment]
Just notice that this is similar to [https://github.com/jamesmbourne/aws4-axios/issues/5](url)
Sorry for the duplicate report.

**Comment by jamesmbourne** [comment]
Thanks for this report @jasonhaihuang 👍 I'll close this in favor of #5 .
